version: "3.9"
services:
  chat-app:
    build:
      context: ./chat-app
    ports:
      - "7001:7001"
    volumes:
      - ./chat-app:/app
      - front_modules:/app/node_modules
  users-service:
    build:
      context: ./users-service
    ports:
      - "7101:7101"
    restart: on-failure
    depends_on:
      - users-service-db
  users-service-db:
    image: mysql:5.7.20
    ports:
      - "7201:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - dbusers:/var/lib/mysql

volumes:
  front_modules: {}
  dbusers: {}
